export const dishes = [
  {
    id: 1,
    name: "Ассорти",
    categoryId: [0, 7],
    imgUrl: "images/menu/Ассорти.jpg",
    price: 370,
    ingredients: "очень вкусные ингридиенты",
    properties: [
      "Без добавок (0р.)",
      "С фри (20р.)",
      "С грибами (10р.)",
      "Острая (10р.)",
    ],
  },
  {
    id: 2,
    name: "Батон",
    categoryId: [0, 9],
    imgUrl: "images/menu/Батон.jpg",
    price: 30,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 3,
    name: "Беарнский",
    categoryId: [0, 6],
    imgUrl: "images/menu/Беарнский соус.jpg",
    price: 70,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 4,
    name: "Борщ",
    categoryId: [0, 2],
    imgUrl: "images/menu/Борщ.jpg",
    price: 120,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 5,
    name: "Вафли с мороженным",
    categoryId: [0, 4],
    imgUrl: "images/menu/Вафли с мороженным.jpg",
    price: 160,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 6,
    name: "Грибной крем-суп",
    categoryId: [0, 2],
    imgUrl: "images/menu/Грибной крем-суп.jpg",
    price: 180,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 7,
    name: "Домашний",
    categoryId: [0, 9],
    imgUrl: "images/menu/Домашний хлеб.jpg",
    price: 40,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 8,
    name: "Огурцовая нарезка",
    categoryId: [0, 1],
    imgUrl: "images/menu/Закуска огурец.jpg",
    price: 90,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 9,
    name: "Крабовый",
    categoryId: [0, 8],
    imgUrl: "images/menu/Крабовый.jpg",
    price: 130,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 10,
    name: "Лимонад",
    categoryId: [0, 5],
    imgUrl: "images/menu/Лимонад.jpg",
    price: 40,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 11,
    name: "Мороженное",
    categoryId: [0, 4],
    imgUrl: "images/menu/Мороженное.jpg",
    price: 75,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 12,
    name: "Мохито",
    categoryId: [0, 5],
    imgUrl: "images/menu/Мохито.jpg",
    price: 65,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 13,
    name: "Пепперони",
    categoryId: [0, 7],
    imgUrl: "images/menu/Пепперони.jpg",
    price: 240,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 14,
    name: "Пироженое",
    categoryId: [0, 4],
    imgUrl: "images/menu/Пироженое.jpg",
    price: 135,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 15,
    name: "Сет роллов",
    categoryId: [0],
    imgUrl: "images/menu/Ролы.jpg",
    price: 560,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 16,
    name: "Домашний",
    categoryId: [0, 8],
    imgUrl: "images/menu/Салат.jpg",
    price: 110,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 17,
    name: "Сметанный",
    categoryId: [0, 6],
    imgUrl: "images/menu/Сметанный.jpg",
    price: 50,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 18,
    name: "Стейк из семги",
    categoryId: [0],
    imgUrl: "images/menu/Стейк из семги.jpg",
    price: 720,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 19,
    name: "Стейк с картошкой фри и помидорами чери",
    categoryId: [0],
    imgUrl: "images/menu/Стейк с картошкой фри и помидорами чери.jpg",
    price: 870,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 20,
    name: "Сырная",
    categoryId: [0, 7],
    imgUrl: "images/menu/Сырная.jpg",
    price: 220,
    ingredients: "очень вкусные ингридиенты",
  },
  {
    id: 21,
    name: "Чизбургер",
    categoryId: [0, 3],
    imgUrl: "images/menu/Чизбургер.jpg",
    price: 210,
    ingredients: "очень вкусные ингридиенты",
  },
];

export const categoryList = [
  {
    name: "Все",
    id: 0,
  },
  {
    name: "Закуски",
    id: 1,
  },
  {
    name: "Супы",
    id: 2,
  },
  {
    name: "Бургеры",
    id: 3,
  },
  {
    name: "Десерты",
    id: 4,
  },
  {
    name: "Напитки",
    id: 5,
  },
  {
    name: "Соусы",
    id: 6,
  },
  {
    name: "Пиццы",
    id: 7,
  },
  {
    name: "Салаты",
    id: 8,
  },
  {
    name: "Хлеб",
    id: 9,
  },
];

export const sortList = [
  { name: "Алфавиту", property: "title" },
  { name: "Сначала дорогие", property: "price", order: "desc" },
  { name: "Сначала дешевые", property: "price", order: "asc" },
];

// [{"id":1,"name":"Ассорти","categoryId":[0,7],"imgUrl":"images/menu/Ассорти.jpg","price":370,"ingredients":"очень вкусные ингридиенты"},{"id":2,"name":"Батон","categoryId":[0,9],"imgUrl":"images/menu/Батон.jpg","price":30,"ingredients":"очень вкусные ингридиенты"},{"id":3,"name":"Беарнский","categoryId":[0,6],"imgUrl":"images/menu/Беарнский соус.jpg","price":70,"ingredients":"очень вкусные ингридиенты"},{"id":4,"name":"Борщ","categoryId":[0,2],"imgUrl":"images/menu/Борщ.jpg","price":120,"ingredients":"очень вкусные ингридиенты"},{"id":5,"name":"Вафли с мороженным","categoryId":[0,4],"imgUrl":"images/menu/Вафли с мороженным.jpg","price":160,"ingredients":"очень вкусные ингридиенты"},{"id":6,"name":"Грибной крем-суп","categoryId":[0,2],"imgUrl":"images/menu/Грибной крем-суп.jpg","price":180,"ingredients":"очень вкусные ингридиенты"},{"id":7,"name":"Домашний","categoryId":[0,9],"imgUrl":"images/menu/Домашний хлеб.jpg","price":40,"ingredients":"очень вкусные ингридиенты"},{"id":8,"name":"Огурцовая нарезка","categoryId":[0,1],"imgUrl":"images/menu/Закуска огурец.jpg","price":90,"ingredients":"очень вкусные ингридиенты"},{"id":9,"name":"Крабовый","categoryId":[0,8],"imgUrl":"images/menu/Крабовый.jpg","price":130,"ingredients":"очень вкусные ингридиенты"},{"id":10,"name":"Лимонад","categoryId":[0,5],"imgUrl":"images/menu/Лимонад.jpg","price":40,"ingredients":"очень вкусные ингридиенты"},{"id":11,"name":"Мороженное","categoryId":[0,4],"imgUrl":"images/menu/Мороженное.jpg","price":75,"ingredients":"очень вкусные ингридиенты"},{"id":12,"name":"Мохито","categoryId":[0,5],"imgUrl":"images/menu/Мохито.jpg","price":65,"ingredients":"очень вкусные ингридиенты"},{"id":13,"name":"Пепперони","categoryId":[0,7],"imgUrl":"images/menu/Пепперони.jpg","price":240,"ingredients":"очень вкусные ингридиенты"},{"id":14,"name":"Пироженое","categoryId":[0,4],"imgUrl":"images/menu/Пироженое.jpg","price":135,"ingredients":"очень вкусные ингридиенты"},{"id":15,"name":"Сет роллов","categoryId":[0],"imgUrl":"images/menu/Ролы.jpg","price":560,"ingredients":"очень вкусные ингридиенты"},{"id":16,"name":"Домашний","categoryId":[0,8],"imgUrl":"images/menu/Салат.jpg","price":110,"ingredients":"очень вкусные ингридиенты"},{"id":17,"name":"Сметанный","categoryId":[0,6],"imgUrl":"images/menu/Сметанный.jpg","price":50,"ingredients":"очень вкусные ингридиенты"},{"id":18,"name":"Стейк из семги","categoryId":[0],"imgUrl":"images/menu/Стейк из семги.jpg","price":720,"ingredients":"очень вкусные ингридиенты"},{"id":19,"name":"Стейк с картошкой фри и помидорами чери","categoryId":[0],"imgUrl":"images/menu/Стейк с картошкой фри и помидорами чери.jpg","price":870,"ingredients":"очень вкусные ингридиенты"},{"id":20,"name":"Сырная","categoryId":[0,7],"imgUrl":"images/menu/Сырная.jpg","price":220,"ingredients":"очень вкусные ингридиенты"},{"id":21,"name":"Чизбургер","categoryId":[0,3],"imgUrl":"images/menu/Чизбургер.jpg","price":210,"ingredients":"очень вкусные ингридиенты"}]
